export default {
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.BasicButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.BasicButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.BrandButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.BrandButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonArrow.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonArrow.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonArrowLeft.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonArrowLeft.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonInnerShadow.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonInnerShadow.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonLiftedShadow.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonLiftedShadow.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonShadowLeft.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonShadowLeft.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonShadowRight.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonShadowRight.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ButtonThreeD.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ButtonThreeD.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.CircleButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.CircleButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.GamingButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.GamingButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.IronButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.IronButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.RibbonButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.RibbonButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ScotchTapeButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ScotchTapeButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ShinyButtonIISkin.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ShinyButtonIISkin.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ShinyButtonInverted.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ShinyButtonInverted.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.ShinyButtonISkin.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.ShinyButtonISkin.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.SloopyButton.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.SloopyButton.v1.png",
  "advancedStylePanel/iconsForSkins/mila.components.skins.button.TextOnlyButtonSkin.png": "/advancedStylePanel/iconsForSkins/wysiwyg.viewer.skins.button.TextOnlyButtonSkin.v1.png",
}
